/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.java1projekt;

import hr.java1projekt.model.Korisnik;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Franjo
 */
public class GlavniEkran extends javax.swing.JFrame {

    private static final String UPLOAD_DELETE_FILMOVA = "Upload i delete filmova";
    private static final String PRIKAZ_FILMOVA = "Prikaz filmova";

    /**
     * Creates new form GlavniEkran
     */
    public GlavniEkran() {
        initComponents();
        lblIme.setText(Korisnik.getIme());
        this.setLocationRelativeTo(null);
        konfigurirajPanele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPaneGlavni = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFilmovi = new javax.swing.JMenu();
        mKategorije = new javax.swing.JMenu();
        miGlumci = new javax.swing.JMenuItem();
        miRedatelj = new javax.swing.JMenuItem();
        miZanr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(1130, 1000));

        jPanel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Pozdrav");

        lblIme.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/java1projekt/assets/login/cancel+danger+error+exit+fault+problem+icon-1320086092655159088_32.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Logout");

        jLabel4.setBackground(new java.awt.Color(0, 102, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("FILMOVI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGlavni.setMinimumSize(new java.awt.Dimension(5, 700));
        jTabbedPaneGlavni.setPreferredSize(new java.awt.Dimension(1100, 700));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPaneGlavni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneGlavni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mFilmovi.setText("Filmovi");
        mFilmovi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mFilmovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFilmoviActionPerformed(evt);
            }
        });
        jMenuBar1.add(mFilmovi);

        mKategorije.setText("Kategorije");
        mKategorije.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        miGlumci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        miGlumci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/java1projekt/assets/menu/theatre.png"))); // NOI18N
        miGlumci.setText("Glumci");
        miGlumci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGlumciActionPerformed(evt);
            }
        });
        mKategorije.add(miGlumci);

        miRedatelj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        miRedatelj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/java1projekt/assets/menu/redatelj.png"))); // NOI18N
        miRedatelj.setText("Redatelji");
        miRedatelj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRedateljActionPerformed(evt);
            }
        });
        mKategorije.add(miRedatelj);

        miZanr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        miZanr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/java1projekt/assets/menu/cinema.png"))); // NOI18N
        miZanr.setText("Žanrovi");
        miZanr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZanrActionPerformed(evt);
            }
        });
        mKategorije.add(miZanr);

        jMenuBar1.add(mKategorije);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        LoginForm loginForm = new LoginForm();
        Logout.logOut(this, loginForm);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void miGlumciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGlumciActionPerformed
        GlumciForm glumciForm = new GlumciForm();
        glumciForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miGlumciActionPerformed

    private void miRedateljActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRedateljActionPerformed
        RedateljiForm redateljiForm = new RedateljiForm();
        redateljiForm.setVisible(true);
        this.dispose();
        }//GEN-LAST:event_miRedateljActionPerformed

    private void miZanrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZanrActionPerformed
        ZanroviForm zanroviForm = new ZanroviForm();
        zanroviForm.setVisible(true);
        this.dispose();
        }//GEN-LAST:event_miZanrActionPerformed

    private void mFilmoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFilmoviActionPerformed
        GlavniEkran glavniEkran = new GlavniEkran();
        glavniEkran.setVisible(true);
        this.dispose();
         }//GEN-LAST:event_mFilmoviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavniEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPaneGlavni;
    private javax.swing.JLabel lblIme;
    private javax.swing.JMenu mFilmovi;
    private javax.swing.JMenu mKategorije;
    private javax.swing.JMenuItem miGlumci;
    private javax.swing.JMenuItem miRedatelj;
    private javax.swing.JMenuItem miZanr;
    // End of variables declaration//GEN-END:variables

    private void konfigurirajPanele() {
        if (Korisnik.getTipKorisnikaID() == 1) {
            jTabbedPaneGlavni.add(UPLOAD_DELETE_FILMOVA, new UploadIDeleteFilmovaPanel());
        }

        jTabbedPaneGlavni.add(PRIKAZ_FILMOVA, new PrikazFilmovaPanel());
    }
}
